apiVersion: v1
kind: Secret
metadata:
  name: demosecret
type: Opaque
data:
  DB_HOST: Y2xvdWQtcGxhdGZvcm0tYWFmYWIyYWEwZTU0NjE5MC5jZHdtMzI4ZGx5ZTYuZXUtd2VzdC0yLnJkcy5hbWF6b25hd3MuY29t
  DB_PORT: NTQzMg==
  DB_USER: Y3AzN1FrZVpacQ==
  DB_PASSWORD: N2lGS1Z4a2l4NTJWRDRwYQ==
  DB_NAME: ZGJhYWZhYjJhYTBlNTQ2MTkw
  ADMIN_USER: YWRtaW4=
  ADMIN_USER: YWRtaW4=1