apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ubistaging-ingress
  namespace: ubi-prod
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: ubistaging-ingress-ubi-prod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  tls:
  - hosts:
    - find-unclaimed-court-money.service.justice.gov.uk
    secretName: prod-fum-cert-secret
  rules:
  - host: find-unclaimed-court-money.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: ubiprod-service
          servicePort: 5001
