apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ubidemo-ingress
  namespace: ubi-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
    location ~* ^/(adminLogin) {
    allow 81.134.202.29/32;
    deny all;
    }
    external-dns.alpha.kubernetes.io/set-identifier: ubidemo-ingress-ubi-dev-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  tls:
  - hosts:
    - development.find-unclaimed-court-money.service.justice.gov.uk
    secretName: dev-fum-cert-secret
  rules:
  - host: development.find-unclaimed-court-money.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: ubidemo-service
          servicePort: 5000
