apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubistaging-ingress
  namespace: ubi-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: ubistaging-ingress-ubi-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
  - hosts:
    - staging.find-unclaimed-court-money.service.justice.gov.uk
    secretName: staging-fum-cert-secret
  rules:
  - host: staging.find-unclaimed-court-money.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ubistaging-service
            port:
              number: 5001