name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'cp'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t ubiwar .